# Generated by Django 5.2.8 on 2025-12-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': '사용자', 'verbose_name_plural': '사용자 목록'},
        ),
    ]
