# Generated by Django 5.2.8 on 2025-12-04 11:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='장소명')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='경도')),
                ('day', models.PositiveIntegerField(default=1, verbose_name='일차')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('planned_time', models.TimeField(blank=True, null=True, verbose_name='예정 방문 시간')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='예상 체류 시간(분)')),
                ('estimated_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='예상 비용')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.CharField(choices=[('attraction', '관광지'), ('restaurant', '음식점'), ('cafe', '카페'), ('accommodation', '숙소'), ('shopping', '쇼핑'), ('transport', '교통'), ('other', '기타')], default='attraction', max_length=20, verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '여행지',
                'verbose_name_plural': '여행지 목록',
                'ordering': ['day', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='여행 제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('thumbnail', models.URLField(blank=True, max_length=500, verbose_name='썸네일 이미지')),
                ('is_public', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('status', models.CharField(choices=[('planning', '계획 중'), ('ongoing', '여행 중'), ('completed', '완료')], default='planning', max_length=20, verbose_name='상태')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '여행',
                'verbose_name_plural': '여행 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', '교통'), ('accommodation', '숙소'), ('food', '식비'), ('attraction', '관광/입장료'), ('shopping', '쇼핑'), ('other', '기타')], max_length=20, verbose_name='카테고리')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='금액')),
                ('description', models.CharField(max_length=200, verbose_name='내용')),
                ('expense_date', models.DateField(verbose_name='지출 날짜')),
                ('expense_time', models.TimeField(blank=True, null=True, verbose_name='지출 시간')),
                ('day_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='일차')),
                ('payment_method', models.CharField(choices=[('cash', '현금'), ('card', '카드'), ('other', '기타')], default='card', max_length=20, verbose_name='결제 수단')),
                ('receipt_image', models.URLField(blank=True, max_length=500, verbose_name='영수증 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='trips.destination', verbose_name='연결된 여행지')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip', verbose_name='여행')),
            ],
            options={
                'verbose_name': '지출',
                'verbose_name_plural': '지출 목록',
                'ordering': ['expense_date', 'expense_time'],
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='trips.trip', verbose_name='여행'),
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100, verbose_name='장소명')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='경도')),
                ('visit_date', models.DateField(verbose_name='방문 날짜')),
                ('visit_time', models.TimeField(blank=True, null=True, verbose_name='방문 시간')),
                ('day_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='일차')),
                ('actual_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='실제 체류 시간(분)')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='평점 (1-5)')),
                ('review', models.TextField(blank=True, verbose_name='후기')),
                ('visit_status', models.CharField(choices=[('planned', '계획대로 방문'), ('unplanned', '계획에 없던 방문'), ('skipped', '계획했지만 미방문')], default='planned', max_length=20, verbose_name='방문 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='trips.destination', verbose_name='연결된 계획')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trips.trip', verbose_name='여행')),
            ],
            options={
                'verbose_name': '여행 기록',
                'verbose_name_plural': '여행 기록 목록',
                'ordering': ['visit_date', 'visit_time'],
            },
        ),
        migrations.CreateModel(
            name='TripLogPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='이미지 URL')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trips.triplog', verbose_name='여행 기록')),
            ],
            options={
                'verbose_name': '여행 사진',
                'verbose_name_plural': '여행 사진 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='일차')),
                ('date', models.DateField(verbose_name='날짜')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_plans', to='trips.trip', verbose_name='여행')),
            ],
            options={
                'verbose_name': '일자별 계획',
                'verbose_name_plural': '일자별 계획 목록',
                'ordering': ['day_number'],
                'unique_together': {('trip', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', '교통'), ('accommodation', '숙소'), ('food', '식비'), ('attraction', '관광/입장료'), ('shopping', '쇼핑'), ('other', '기타')], max_length=20, verbose_name='카테고리')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='예산 금액')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='trips.trip', verbose_name='여행')),
            ],
            options={
                'verbose_name': '예산',
                'verbose_name_plural': '예산 목록',
                'ordering': ['category'],
                'unique_together': {('trip', 'category')},
            },
        ),
    ]
