# Generated by Django 5.2.8 on 2025-12-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='썸네일 이미지'),
        ),
    ]
